스냅(중앙, 오브젝트간) 기능 추가
toonsquare/fabric.js pull request #7
Opened 2022-07-11 08:32 UTC by dodo-Riley

### 해결하려는 문제
- 캔버스 내 오브젝트 간 스냅 및 가이드 라인 추가
- 캔버스 내 하얀 부분(guidemask)을 기준으로 가로/세로 중앙 스냅 및 가이드 라인 추가

### 해결 방법
- 기존 fabricjs에 존재하는 aligning_guidelines.js 파일을 수정
- 처음 에디터에 들어올 경우, 스냅 기능 활성화된 상태 -> 더보기란에서 기능 끌수 있도록 토글 추가
- stroke 색상을 주황색으로 변경
- 일부 변경해줘야하는 변수 수정(기존 fabric에서 canvas.contextTop을 ctx로) : 해주지 않으면 before:render관련 이벤트 핸들에서 에러 발생함

1. 오브젝트 간 스냅
- 기존에는 각 오브젝트의 상하좌우가 각각 상은 상끼리, 좌는 좌끼리 등 같은 방향인 경우에만 스냅 기능이 활성화되었으나, 각 오브젝트의 상하좌우가 반대여도 활성화되도록 코드 추가
- 오브젝트 간의 경우, 점선으로 선이 표시되도록 함

2. 중앙 스냅
- tooning의 특징(canvas가 아닌 guidemask를 기준으로)에 맞춰 코드 수정
- guidemask는 하나의 오브젝트이므로 fabricjs에 기 존재하던 centering_guidelines.js를 이용할 필요없음
- 중앙 스냅의 경우 실선으로 선이 표시되도록 함

### 첨부
- 동작 화면
![스냅완성](https://user-images.githubusercontent.com/96458726/178220527-8b4187bc-6f49-446c-b50e-214ad2200230.gif)

- pr 머지되면 tooning repo에서 수정한 코드도 pr 올릴 예정(함수, 토글 추가 등 수정사항 존재)

2022-07-11 09:16 UTC, PigGgokio requested changes

2022-07-11 09:16 UTC, PigGgokio commented on lib/aligning_guidelines.js
> +  function drawCenterLine(coords) {
이건 왜 생성 했는지 알수 있을까요?
drawLine() 수정하는거랑 차이가 없어보이네요

2022-07-12 00:14 UTC, dodo-Riley commented on lib/aligning_guidelines.js
> +  function drawCenterLine(coords) {
drawVerticalLine/drawHorizontalLine과 구분하기 위해서 새로 생성했는데 굳이 필요는 없습니다. 삭제하고 아래 반복문쪽에 drawLIne 그대로 쓰는 걸로 수정했습니다!

2022-07-14 00:05 UTC, PigGgokio approved these changes

2022-07-14 07:53 UTC, mwmw7 requested changes

2022-07-14 07:53 UTC, mwmw7 commented on lib/aligning_guidelines.js
> +    canvas.on('mouse:down', beforeSnap);
혹시 에디터쪽으로 들어 올때 마다 매번 on이되면서 이벤트랑 이벤트헨들러를 세팅하게 되지는 않나요?

2022-07-14 08:01 UTC, merged